version: '3.1'

services:
  db:
    image: mariadb:10.6
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: notSecureRootPassword
    deploy:
      resources:
        limits:
          cpus: '10.0'  # Limit to 2 CPU cores
          memory: '4G'       # Limit to 4GB of RAM
        reservations:
          cpus: '1.0'  # Reserve at least 1 CPU core
          memory: '2G'       # Limit to 4GB of RAM

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
    deploy:
      resources:
        limits:
          cpus: '1.5'        # Limit to 1.5 CPU cores
          memory: '2G'       # Limit to 2GB of RAM
        reservations:
          cpus: '0.5'        # Reserve at least 0.5 CPU core
          memory: '1G'       # Reserve at least 1GB of RAM